[ 2024-11-18 15:37:45,684 ] 22 root - INFO - Data Ingesion has been started
[ 2024-11-18 15:37:45,684 ] 24 root - INFO - Data reading using Pandas from local file system
[ 2024-11-18 15:37:45,744 ] 26 root - INFO - Data Reading has been completed
[ 2024-11-18 15:37:45,885 ] 30 root - INFO - Raw data has been stored
[ 2024-11-18 15:37:45,889 ] 33 root - INFO - Raw data has been splitted into Train and Test set
[ 2024-11-18 15:37:46,027 ] 38 root - INFO - Data Ingestion has been completed!
[ 2024-11-18 15:37:46,027 ] 49 root - INFO - Created feature store configuration at /home/tahnik/MWC-Module-3-Modular-Workflow-and-Project-Setup-Basics/feature_repo/feature_store.yaml
[ 2024-11-18 15:37:46,028 ] 53 root - INFO - Configuration file content:
project: income_prediction
provider: local
registry: data/registry.db
online_store:
  type: sqlite
offline_store:
  type: file
entity_key_serialization_version: 2
[ 2024-11-18 15:37:46,776 ] 57 root - INFO - Feature store initialized successfully
[ 2024-11-18 15:37:46,836 ] 110 root - INFO - Read train and test data completed
[ 2024-11-18 15:37:46,837 ] 111 root - INFO - Obtaining preprocessing object
[ 2024-11-18 15:37:46,837 ] 65 root - INFO - Data Transformation Started
[ 2024-11-18 15:37:46,842 ] 126 root - INFO - Applying preprocessing object on training and testing datasets.
[ 2024-11-18 15:37:46,957 ] 131 root - INFO - Starting feature store operations
[ 2024-11-18 15:37:47,149 ] 176 root - INFO - Saved feature data to feature_repo/data/train_features.parquet
[ 2024-11-18 15:37:47,153 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-18 15:37:47,158 ] 409 root - WARNING - Cannot use sqlite_vec for vector search
[ 2024-11-18 15:37:47,164 ] 215 root - INFO - Applied entity and feature view for train
[ 2024-11-18 15:37:47,164 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-18 15:37:47,167 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-18 15:37:47,169 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-18 15:38:05,350 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-18 15:38:09,556 ] 222 root - INFO - Materialized features successfully
[ 2024-11-18 15:38:09,556 ] 135 root - INFO - Pushed training data to feature store
[ 2024-11-18 15:38:09,580 ] 176 root - INFO - Saved feature data to feature_repo/data/test_features.parquet
[ 2024-11-18 15:38:09,583 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-18 15:38:09,592 ] 215 root - INFO - Applied entity and feature view for test
[ 2024-11-18 15:38:09,593 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-18 15:38:09,597 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-18 15:38:09,598 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-18 15:38:34,828 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-18 15:38:37,727 ] 222 root - INFO - Materialized features successfully
[ 2024-11-18 15:38:37,727 ] 138 root - INFO - Pushed testing data to feature store
[ 2024-11-18 15:38:38,276 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cde28ece0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Prediction_Pipeline
[ 2024-11-18 15:38:42,966 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cde28eef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Prediction_Pipeline
[ 2024-11-18 15:38:51,444 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cde28f0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Prediction_Pipeline
[ 2024-11-18 15:39:08,413 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cde28f250>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Prediction_Pipeline
[ 2024-11-18 15:39:41,174 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cde28f400>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Prediction_Pipeline
